### ISSUE TITLE
Nothing returned

### ISSUE THREAD

**Issue by TymekV** [kbaraniak/librus-api-rewrited#14]
Functions should return data instead of logging it to console (version in npm)

**Comment by kbaraniak** [comment]
Thanks for report. Problem fixed in release 1.21, please test the latest version. You can try API, using https://github.com/kbaraniak/librus-api-rewrited/blob/master/examples/test.js.
If you have problem again, reopen this issue

**Thanks for usage**
Kamil

**Comment by kbaraniak** [comment]
**Updated version**: https://www.npmjs.com/package/librus-api-rewrited/v/1.2.1
